import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ATLAS School</title>
        <meta name="The Ministry of Education, private school atlas school" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <ul className='nemu-bar'>
          <li>
            <a href='/home'>Accueil</a>
            <a href='/Activities'>Activités</a>
            <a href='/about'>A propos</a>
            <a href='/register'>Préinscription</a>
            <a href='/blog'>Blog</a>
            <a href='/contact'>Contact</a>
            <a href='/login'>Se connecter</a>
          </li>
        </ul>
      </nav>

      <main className={styles.main}>
        <div className={styles.grid}>
        <h1 className="text-3xl font-bold">
          Hello world!
        </h1>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/abdelaziz.bakir.z"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by{' '}
          <span className={styles.logo}>
            <Image src="/abz.ico" alt="ABZ Logo" width={40} height={20} />
          </span>
        </a>
      </footer>
    </div>
  )
}
