import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import {children} from 'react';
import styles from '../styles/Home.module.css'

const layout = {(children)} => {
    return (
        <div>
      <Head>
        <title>ATLAS School</title>
        <meta name="The Ministry of Education, private school atlas school" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       {children}
        </div>
    );
};
export default layout;