import React from 'react'
import Head from 'next/head'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'

const Layout = ({children}) => {
    return (
        <> 
          <Head>
            <title>ATLAS School</title>
            <meta name="The Ministry of Education, private school atlas school" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="../styles/Home.module.css" />  
          </Head>
          <NavBar />
          <main className={styles.main}>{children}</main>
          <Footer />
        </>
    )
}

export default Layout
